version: "3.8.1"
services:
  client:
    build:
      context: ./search-engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
    # volumes:
      # - ./search-engine:/app
    command: flask run --host=0.0.0.0 --port=5000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - dev

  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    deploy:
      replicas: ${ENABLE_DEV_SERVICE:-0}

