version: "3.8.1"
services:
  web:
    build:
      context: ./search-engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
    ### For dev
    volumes:
      - ./search-engine:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ###

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
