version: '3.8.1'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    volumes: 
      - dev-data:$PWD/fhe_directory

volumes:
  dev-data: